export const GET_POKEMON = 'GET_POKEMON'
export const GET_POKEMON_PRELOAD = 'GET_POKEMON_PRELOAD'
export const GET_POKEMON_DETAIL = 'GET_POKEMON_DETAIL'
export const GET_POKEMON_DETAIL_PRELOAD = 'GET_POKEMON_DETAIL_PRELOAD'
